name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Flake check
        run: nix flake check
      - name: Nix build
        run: nix build '.#default'
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo test
        run: cargo test --workspace
      - name: Build OCI image (amd64)
        run: nix build .#packages.x86_64-linux.dockerImage-amd64
