name: publish-flakehub

on:
  push:
    branches: [main]

jobs:
  flakehub:
    uses: pleme-io/substrate/.github/workflows/reusable-flakehub.yml@main
    with:
      visibility: public
      rolling: true
    permissions:
      id-token: write
      contents: read
